### ISSUE TITLE
New Installation Ubuntu not working

### ISSUE THREAD

**Issue by tgarbin** [franton/JSS-In-A-Box#10]
Hello,

as requested here is the issue I am having:

On a fresh install of Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-81-generic x86_64)

after downloading and running the latest version of the script, it installs all files without error but I am unable to browse the address https://<ip>:8443 

Looking in the catalina.out logs I can see:

> 22-Jun-2017 18:51:22.733 SEVERE [main] org.apache.tomcat.util.digester.Digester.fatalError Parse Fatal Error at line 95 column 5: Element type "Connector" must be followed by either attribute specifications, ">" or "/>".
>  org.xml.sax.SAXParseException; systemId: file:/opt/tomcat8/conf/server.xml; lineNumber: 95; columnNumber: 5; Element type "Connector" must be followed by either attribute specifications, ">" or "/>".
>

Adding /> to the end of the https section of the server.xml allows it to load.

Another problem is that MySQL will install then if you check again, it will report that it's not installed and attempt to reinstall. 

running the check after it installs shows the following:

$ dpkg -l | grep mysql
ii  mysql-apt-config                   0.8.3-1                                    all          Auto configuration for MySQL APT Repo.
ii  mysql-client                       5.7.18-1ubuntu16.04                        amd64        MySQL Client meta package depending on latest version
ii  mysql-common                       5.7.18-1ubuntu16.04                        amd64        MySQL Common
ii  mysql-community-client             5.7.18-1ubuntu16.04                        amd64        MySQL Client
ii  mysql-community-server             5.7.18-1ubuntu16.04                        amd64        MySQL Server
ii  mysql-server                       5.7.18-1ubuntu16.04                        amd64        MySQL Server meta package depending on latest version

Thanks!

**Comment by franton** [comment]
the mysql 5.7 stuff is a known issue. one day when I have actual spare time, I'll take a more in depth look as I don't like what they've done with a lot of it.

Can you supply the config you're using, as specified in the variables at the start of the script? My usual use doesn't involve HTTPS which I suspect you're using?

**Comment by franton** [comment]
Also which version of JSS in a Box please?

**Comment by franton** [comment]
Never mind, found it. Stupid bug fixed. V4.5 now released.
