### ISSUE TITLE
Curling Tomcat Version adding White space Ubuntu 16.04.3

### ISSUE THREAD

**Issue by mks-007** [franton/JSS-In-A-Box#11]
OS: Ubuntu 16.04.3 (inline upgrade from 14.10)

Line 671  version=$( curl -s http://tomcat.apache.org/download-80.cgi | grep "<h3 id=\"8.0" | head -n1 | awk '{gsub("<[^>]*>", "")}1')

Version:                             8.0.47

Downloading and installing latest Tomcat 8
--2017-10-04 11:56:40--  http://www.apache.org/dist/tomcat/tomcat-8/v%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%208.0.47/bin/apache-tomcat-%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%208.0.47.tar.gz
Resolving www.apache.org (www.apache.org)... 88.198.26.2, 140.211.11.105, 62.210.60.236, ...
Connecting to www.apache.org (www.apache.org)|88.198.26.2|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-04 11:56:40 ERROR 404: Not Found.

tar (child): /opt/apache-tomcat-                            8.0.47.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mv: cannot stat ‘/opt/apache-tomcat-                            8.0.47’: No such file or directory
rm: cannot remove ‘/opt/apache-tomcat-                            8.0.47.tar.gz’: No such file or directory

adding | awk ‘{print $NF’} ) to the end of line 671 as a temporary fix

**Comment by franton** [comment]
Fixed (hopefully) in v4.91 which I've just released.
