### ISSUE TITLE
maxPostSize?

### ISSUE THREAD

**Issue by jamesez** [franton/JSS-In-A-Box#12]
Am I correct in line 1124's maxPostSize is overridden on line 1124?

https://github.com/franton/JSS-In-A-Box/blob/a67ed6ddafe76aef81631526737d741c352a47a7/jss-in-a-box.sh#L1122

https://github.com/franton/JSS-In-A-Box/blob/a67ed6ddafe76aef81631526737d741c352a47a7/jss-in-a-box.sh#L1124

**Comment by franton** [comment]
Sorry about the delay, but you logged that just as I went on vacation.

Anyway v5.3 released that should deal with that.
