### ISSUE TITLE
Won't start..

### ISSUE THREAD

**Issue by sggr57a** [franton/JSS-In-A-Box#4]
I love the product you've created.  It was really easy to install and I'm excited how much time it will save me to bring up JSS environments in a flash.  I am having trouble however starting up the web page.  Since this instance wasn't set up the same way as the jar file from JAMF I'm not sure what to look for.  Tomcat appears to be running as well as MySQL and nothing gave me an error when you're installer ran.  Can you help me out?

**Comment by franton** [comment]
This is meant to be used on a blank server. If you've run this on an existing server, bad things will happen. Is that the case?

What's the error message you are getting?

**Comment by sggr57a** [comment]
The script doesn't give me any error.  However when I attempt to connect to the server in a browser after creating the ROOT instance I can't connect to it.  It's as if it doesn't exist at all.

**Comment by sggr57a** [comment]
The server IS a VM though.

**Comment by franton** [comment]
You are using (assuming no HTTPS stuff) http://address:8080 ?

Also check the firewall settings, and any of the internal variables at the top of the script. Make sure they're ok.

**Comment by sggr57a** [comment]
I followed your video to the T so I was assuming I'd be albe to connect using https and 8443 but is that not the case?  What do I need to change for the firewall and can I just disable it altogether for testing?

**Comment by franton** [comment]
By default JSS-in-a-Box does not set up HTTPS functionality. That is enabled within the script itself. Blank your vm and start again, but before running the script make sure the internal variables at the top are set correctly.

LetsEncrypt functionality requires the server be accessible from the internet or the verification process will fail.

**Comment by sggr57a** [comment]
Oh I did set them up at the beginning.  I think the vm network adapter may be the issue as you alluded to.

**Comment by sggr57a** [comment]
I don't think that Tomcat is actually running.  How can I troubleshoot this with regard to your installation?

**Comment by sggr57a** [comment]
Do you have a check to make sure tomcat 8 is running when you should be able to load the JSS web page?

**Comment by sggr57a** [comment]
It looks as though it keeps shutting down after a few seconds.  Check out this output..

john@jss-dev-test:~$ sudo service tomcat status
tomcat start/running, process 3863
john@jss-dev-test:~$ sudo service tomcat status
tomcat start/running, process 3914
john@jss-dev-test:~$ sudo service tomcat status
tomcat start/running, process 3965
john@jss-dev-test:~$ sudo service tomcat status
tomcat start/running, process 4016
john@jss-dev-test:~$ sudo service tomcat status
tomcat stop/waiting
john@jss-dev-test:~$ sudo service tomcat status
tomcat stop/waiting
