### ISSUE TITLE
Tomcat 8 keeps crashing..

### ISSUE THREAD

**Issue by sggr57a** [franton/JSS-In-A-Box#5]
I don't think that Tomcat is actually running. How can I troubleshoot this with regard to your installation?

**Comment by sggr57a** [comment]
Do you have a check to make sure tomcat 8 is running when you should be able to load the JSS web page?

**Comment by sggr57a** [comment]
It looks as though it keeps shutting down after a few seconds. Check out this output..

john@jss-dev-test:~$ sudo service tomcat status
tomcat start/running, process 3863
john@jss-dev-test:~$ sudo service tomcat status
tomcat start/running, process 3914
john@jss-dev-test:~$ sudo service tomcat status
tomcat start/running, process 3965
john@jss-dev-test:~$ sudo service tomcat status
tomcat start/running, process 4016
john@jss-dev-test:~$ sudo service tomcat status
tomcat stop/waiting
john@jss-dev-test:~$ sudo service tomcat status
tomcat stop/waiting

**Comment by franton** [comment]
Unless you state the following, I cannot help you. I would only be guessing.

1) Which OS did you use?
2) What options did you set in the variables for JSS in a Box?
3) The relevant output from /opt/tomcat/logs/catalina*.out

There are different error outputs depending on OS used.

**Comment by sggr57a** [comment]
1) Ubuntu 14.04
2) I only set admin user, passwords and SSL to true for letsencrypt
3) already checked, logs don't exist

**Comment by franton** [comment]
Pushed a new version with a lot of HTTPS stuff. Blank your VM and give that a try.

**Comment by sggr57a** [comment]
Ok done and still no dice.  When I attempt to renew SSL certs I get this message so I'm hoping it tells you something more than it does me.

Choose an option (1-9 / q) : 9

Stopping Tomcat service

tomcat stop/waiting

Obtaining Certificate from LetsEncrypt Certificate Authority

*\* DRY RUN: simulating 'certbot renew' close to cert expiry
*\*          (The test certificates below have not been saved.)

No renewals were attempted.
*\* DRY RUN: simulating 'certbot renew' close to cert expiry
*\*          (The test certificates above have not been saved.)
rm: cannot remove ‘/opt/tomcat8/keystore/keystore.jks’: No such file or directory

Merging LetsEncrypt certificates into a PKCS12 file
Error opening input file /etc/letsencrypt/live/jss-dev-test.newton.edu/fullchain.pem
/etc/letsencrypt/live/jss-dev-test.newton.edu/fullchain.pem: No such file or directory

Converting PKCS12 file into a Java KeyStore
keytool error: java.io.FileNotFoundException: /opt/tomcat8/keystore/fullchain_and_key.p12 (No such file or directory)
rm: cannot remove ‘/opt/tomcat8/keystore/fullchain_and_key.p12’: No such file or directory

**Comment by franton** [comment]
Ok and how are the variables set at the top of the script?

**Comment by sggr57a** [comment]
export useract="john"                               # Server admin username. Used for home location.

export letsencrypt="TRUE"                                   # Set this to TRUE if you are going to use LetsEncrypt as your HTTPS Certificate Authority.
export sslTESTMODE="TRUE"                                   # Set this to FALSE when you're confident it's generating proper certs for you
export httpsredirect="FALSE"                                # Set this to TRUE if you want your JSS to appear to be on port 443 using HTTPS
export ssldomain="myhostname.newton.edu"    # Domain name for the SSL certificates
export sslemail="user@ourdomain.edu"                # E-mail address for the SSL CA
export sslkeypass="den1ed"                              # Password to the keystore. Default is "changeit". Please change it!

export mysqluser="root"                                     # MySQL root account
export mysqlpw="password"                                   # MySQL root account password. Please change it!
export mysqlserveraddress="localhost"                       # IP/Hostname of MySQL server. Default is local server.

export dbuser="jamfsoftware"                                # Database username for JSS
export dbpass="password"                                    # Database password for JSS. Default is "changeit". Please change it!

**Comment by franton** [comment]
Ok.

After you ran this on a blank server, did it generate the test certificates and put them in the keystore? Running option 9 immediately after isn't a recommended option while variable sslTESTMODE="TRUE" .

If you ran this on an existing server built by a previous build, anything could happen.

**Comment by sggr57a** [comment]
No I only ran it because I needed a direction to go in.  How would I know exactly if the test certificates were created or not?  Where and what would I need to do?

**Comment by sggr57a** [comment]
The jar file from jamf worked perfectly once I installed the dependencies manually.  I'd really like to avoid doing that in the future and use your product though.
