### ISSUE TITLE
Does not correctly detect CentOS 7

### ISSUE THREAD

**Issue by rsaeks** [franton/JSS-In-A-Box#7]
Current code for detecting CentOS 7 does not work. 

Actual output:

cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

Line reading:
cat /etc/redhat-release | awk '{ print $7 }' | cut -c 1
changed to:
cat /etc/redhat-release | awk '{ print $4 }' | cut -c 1

pulls correct version.

**Comment by franton** [comment]
This script does not support anything other than Jamf recommended OS versions. CentOS checking is therefore not built in. I know you can run this on CentOS but I'm sticking to what's officially supported, sorry.
