### ISSUE TITLE
LetsEncrypt Challenge

### ISSUE THREAD

**Issue by frogstar** [franton/JSS-In-A-Box#8]
Not so much a Issue, but a note/question: in order to get LetsEncrypt to run through without error, i had to forward 443 to the Server as well.

Can this be avoided?

Does this portforward need to remain in place for the Cert-Update to happen?

**Comment by franton** [comment]
That may be a change on LetsEncrypt side of things. Interesting to note: thanks for the tip. I'll include firewall config changes with the next release.

**Comment by franton** [comment]
Ok just gone through the code. I do enable 443 on the server end firewall. Anything occurring after that point is infrastructure environment related I'm afraid. Specifically L804 for Ubuntu and L844 for RedHat.

If you're having to forward ports from elsewhere to the server for HTTPS, you should continue to do so. A lot of Apple specific traffic is now 443 only. Hope that helps.

**Comment by frogstar** [comment]
Hi and thanks for the quick response. I was hoping you might have played around with it already and would know if the portforward is a permanent requirement. apparently LetsEncrypt want to be able to reach the Server unter its public ip on Port 443. Which would mean that only one Server can leverage LetsEncrypt from one Public IP. I dont think that is how it should be, but will continue to search in the corresponding forums. However - might be worth noting that in the script - "Please make sure you forward port 443 to your Server in order for LetsEncrypt to be able to verify the Server". :)
