### ISSUE TITLE
JSS not running after running the Script

### ISSUE THREAD

**Issue by frogstar** [franton/JSS-In-A-Box#9]
Hi,
i did a fresh Ubuntu 16.04 installation and run the script. It was running nicely. 
Fort the Option 1) to install
then Option 3) to setup ROOT Instance

Unfortunately if i try to access the URL, there is nothing answering. So i assume something went wrong. Before i start searching for hours - is there any log or something i could provide to identify the issue?

**Comment by franton** [comment]
What's the URL you're using? It'll be port 8080 for HTTP requests and 8443 for HTTPS requests, unless you've got the 443 firewall rule enabled.

I'm running this quite happily in my test VM's currently.

The only log files that will provide any clues are the Tomcat ones. That'll be in /opt/tomcat8/logs ... specifically the Catalina ones.

**Comment by frogstar** [comment]
I was expecting 8443 to work - but did not.
Also tried 443 - did not work either. 
Did not test 8080 yet, but will do so later. 
Traveling now, so i don't have access to the Server today.

**Comment by franton** [comment]
Yeah check the variables at the top of the script to see how it's been configured. Then see which connector is enabled in the Tomcat server.xml file. By default, you get a HTTP only server so you have to specifically enable the other stuff before running. Let me know how you get on.

**Comment by frogstar** [comment]
Ok, then i was misinterpreting the Variables. My understanding was that it will always setup https via 8443 and the https-option is only to redirect https to 443. 
What value will i need to change to get https on 8443 then?

**Comment by franton** [comment]
Line 78 to enable LetsEncrypt. Set to TRUE.
Line 79 to use LetEncrypt testing mode until your happy it'll work.
Line 80 for the HTTPS redirection. Set that to FALSE for port 8443.
Lines 81-83 for the rest of the LetsEncrypt configuration.

That'll take care of things.

**Comment by frogstar** [comment]
Well, thats exactly the setup i used. Besides the LetsEncrypt Test-mode - thats probably still at TRUE. Can i set it to False and just run the script again?

**Comment by franton** [comment]
Should be ok to do so.

**Comment by franton** [comment]
This is why I recommend testing on VM's first before going production. So much to go wrong, reverting a snapshot is easy ;)

**Comment by franton** [comment]
I assume you got this working.

**Comment by tgarbin** [comment]
Hello, 

I'm not sure if this is the same issue but on a fresh install I also had trouble running tomcat.

In my catalina.out was the line

> WARNING [main] org.apache.catalina.startup.Catalina.load Catalina.start using conf/server.xml: The element type "Connector" must be terminated by the matching end-tag "\</Connector>".

There is a missing /> on line [1117](https://github.com/franton/JSS-In-A-Box/blob/2d28d43050093ebb7c864f684b93a8f7913cab3e/jss-in-a-box.sh#L1117). This may be from d06f373 where the following line containing the closing /> was removed 

sed -i '91i\    \t\tclientAuth="false" serverclientAuth="false"/>' $server

Once I added /> on the end of the ciphers, it worked fine.

**Comment by franton** [comment]
Please make sure you are using the latest version. If you're still having issues, please submit all the settings you are using in a new ticket thanks!
